### ISSUE TITLE
[Bug]: `East limit may be insufficient` while running geocoded SLC

### ISSUE THREAD

**Issue by yunjunz** [opera-adt/COMPASS#24]
### Checked for duplicates

Yes - I've already checked

### Describe the bug

When I was running `s1_cslc.py -g geo s1_cslc_geo_20200511.yaml`, I noticed the `journal` output of `East limit may be insufficient for global height range`, is this a warning indicating something wrong in the processing? 

```bash
journal: Starting s1_geocode_slc burst
Chi squared: 0.000029
nbands: 3
nBlocks: 4
block: 0
-116.698 , 0.1 , 37.9453, 38.2456
journal: East limit may be insufficient for global height range
DEM interpolation Done
journal:
 -- Actual DEM bounds used:
 -- Top Left: -116.698 38.2457
 -- Bottom Right: -114 37.9454 
 -- Spacing: 0.000277778 -0.000277778
 -- Dimensions: 9713 1082
band: 0
get data block 
set output 
band: 1
get data block 
set output 
band: 2
get data block 
set output 
```

I am sure that my DEM (prepared using isce2/dem.py) covers the entire burst (and the entire track).

Here is the output amplitude of the SLC.

<img width="1648" alt="Screen Shot 2022-05-16 at 9 25 20 PM" src="https://user-images.githubusercontent.com/13143710/168728781-8f81d27b-9723-487f-9619-1a9dd439ca71.png">

### What did you expect?

I expected [...]

### Reproducible steps

```bash
s1_cslc.py -g geo s1_cslc_geo_20200511.yaml
```

### Environment

```bash
- Version of this software: version 0.1 (the latest main branch on github)
- Operating System: Linux (Red Hat 7.9)
...
```

**Comment by hfattahi** [comment]
It's a warning but it should not be there if the DEM covers the area. You can check if isce3 understand the extent of your DEM correctly:

```
dem = isce3.io.Raster(dem_file)
print(dem.get_geotransform())
```

How is your geogrid setup in your input Yaml file?

**Comment by hfattahi** [comment]
BTW, in the error message I see ```-116.698 , 0.1 , 37.9453, 38.2456```, which seems to indicate "west, east, south north". The only value that does not make sense is ```east``` which is 0.1, which is the default DEM margin in degrees. That seems a bit strange. But let's make sure if you are passing in the correct geogrid in your Yaml file.

**Comment by yunjunz** [comment]
Here is the isce3 checking of my DEM, which seems reasonable to me.

```bash
(opera) kamb:~/data-marmot/OPERA/DEM>$ python
Python 3.9.0 | packaged by conda-forge | (default, Nov 26 2020, 07:57:39) 
[GCC 9.3.0] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import isce3
>>> dem_file = 'demLat_N37_N40_Lon_W119_W114.dem.wgs84'
>>> dem = isce3.io.Raster(dem_file)
>>> print(dem.get_geotransform())
[-119.0, 0.0002777777777777778, 0.0, 40.0, 0.0, -0.0002777777777777778]
>>> 
```

And my YAML file, I did not change anything in `processing/geocoding`

```yaml
runconfig:
  name: cslc_s1_workflow_default

  groups:
      pge_name_group:
          pge_name: CSLC_S1_PGE

      input_file_group:
          # Required. List of SAFE files (min=1)
          safe_file_path: ['/home/zyunjun/data-marmot/OPERA/SLC/S1A_IW_SLC__1SDV_20200511T135117_20200511T135144_032518_03C421_7768.zip']
          # Required. List of orbit (EOF) files (min=1)
          orbit_file_path: ['/home/zyunjun/bak/aux/aux_poeorb/S1A_OPER_AUX_POEORB_OPOD_20210318T120818_V20200510T225942_20200512T005942.EOF']
          # Required. Path to the burst data
          burst_file_path:  str(required=True)
          # Required. Path to light metadata file
          light_metadata_path: str(required=True)
          # Required. List of unique burst IDs to process
          burst_id: t71_iw1_b848

      dynamic_ancillary_file_group:
          # Digital elevation model
          dem_file: /home/zyunjun/data-marmot/OPERA/DEM/demLat_N37_N40_Lon_W119_W114.dem.wgs84

      product_path_group:
          # Directory where PGE will place results
          product_path: /home/zyunjun/data-marmot/OPERA/compass_gslc/gslc
          # Directory where SAS writes temporary data
          scratch_path: /home/zyunjun/data-marmot/OPERA/compass_gslc/scratch
          # Intermediate file name. SAS writes the output to this file.
          # PGE may rename the product according to file naming convention
          sas_output_file: /home/zyunjun/data-marmot/OPERA/compass_gslc/sas_output_file

      processing:
          polarization: co-pol
          geocoding:
              output_format: ENVI
              flatten: True
              # Dem margin (in units of input DEM)
              dem_margin: 0.1
              lines_per_block: 1000
              output_epsg:
              x_posting:
              y_posting:
              x_snap:
              y_snap:
              top_left:
                  x:
                  y:
              bottom_right:
                  x:
                  y:
```
